### ISSUE TITLE
CodeTour Question

### ISSUE THREAD

**Issue by lostintangent** [vouch-dev/vscode-vouch#1]
Hi! 👋  I'm the maintainer of the CodeTour extension, and I just noticed Vouch show up in the VS Code marketplace. Out of curiosity: were there any specific requirements that you were interested in driving into CodeTour? I just ask since I'm keen to collaborate with the community on the experience, and help create more ubiquity with the tour format. That said, if there were any collaboration opportunities, I'd love to hear about that. Thanks! 🙌

**Comment by rndhouse** [comment]
Hello @lostintangent ! Thanks for reaching out, CodeTour extension is very cool. I've always wanted a tool which can help introduce new developers to a code base.

> were there any specific requirements that you were interested in driving into CodeTour?

Not really. CodeTour seemed like a good starting point. But the Vouch VSCode extension is trying to solve a different problem.

You said this in your Reddit [comment](https://www.reddit.com/r/javascript/comments/mqff8s/vouch_a_dependency_review_tool_for_npm_packages/):
> I’d love to learn more about the direction you’re planning on going

The Vouch VSCode extension aims to make it easier to review software packages and share those reviews. Those reviews can then be aggregated and used to evaluate software dependencies for security or quality.

The VSCode extension was intended to be used via the Vouch command line tool: https://github.com/vouch-dev/vouch

The extension will certainly need to be re-designed. As it stands it should be enough to evaluate whether this idea is viable.

I would be happy to hear any ideas or suggestions you may have!

(I will reply sooner next time, I did not see your message until you posted on Reddit.)

**Comment by lostintangent** [comment]
Got it. I just wanted to confirm that you were explicitly "white-labeling" the extension and not interested in collaborating on CodeTour requirements. Thanks!
